### ISSUE TITLE
Your plugin folder does not exist.

### ISSUE THREAD

**Issue by ripsnortntear** [budesaal/Rebornbuddy-Profiles#1]
You will need ExBuddy installed in your plugins folder which can be found here https://github.com/Entrax643/ExBuddy You will need to take the ExTurnInGuildLeveTag.cs file from my Plugins folder and place it in RebornBuddy\Plugins\ExBuddy\OrderBotTags\Behaviors folder, overwriting the current one. This files makes some changes to fix the GuildLeve turn ins.

where can i get your ExTurnInGuildLeveTag.cs file

**Comment by beckyeeky** [comment]
I guess this is referring to https://github.com/Angles24/ZodiacWeapons/blob/master/Plugins/ExTurnInGuildLeveTag.cs
